name: SEO Ping on Push

on:
  push:
    branches:
      - master

jobs:
  ping-search-engines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run SEO Ping Script
        run: node seo-ping.js
